### ISSUE TITLE
Making it installable by anyone who intend to use it

### ISSUE THREAD

**Issue by MPins** [uwla/lnpaywall#2]
@uwla is going to make changes to make the lnpaywall installable by anyone who intend to use it. As soon as the changes are ready I'm going to test it. Target date 11/19/23

**Comment by uwla** [comment]
Well, I actually have done it... (therefore, I'm closing it)

Anyone can clone the repo, follow the README instructions and use it.

A couple of days ago, I've made it possible to use LNPaywall with any docker container (as explainded in the README).

Therefore, anyone could already set up LNPaywall with an existing webservice (streaming, gaming, editing, collaboration, video conference, etc).

I plan to set it up with a self-hosted JITSI instance: you pay some sats to enjoy private video conference.

The project is usable, but still has a lot to improve:
- make installation easier (without technical knowledge)
- add some demo webapps
- add automated tests

Among other things that may come along the way.
